LOCATION_TO_ID_MAP = {
    ["Win Condition/AllWin/Eternatus"] = 1,
    ["Pokemon/Routes/Blipbug"] = 2
    ["Pokemon/Routes/Caterpie"] = 3
    ["Pokemon/Routes/Grubbin"] = 4
    ["Pokemon/Routes/Hoothoot"] = 5
    ["Pokemon/Routes/Nickit"] = 6
    ["Pokemon/Routes/Rookidee"] = 7
    ["Pokemon/Routes/Skwovet"] = 8
    ["Pokemon/Routes/Wooloo"] = 9
    ["Pokemon/Routes/Lotad"] = 10
    ["Pokemon/Routes/Seedot"] = 11
    ["Pokemon/Routes/Purrloin"] = 12
    ["Pokemon/Routes/Galarian Zigzagoon"] = 13
    ["Pokemon/Routes/Chewtle"] = 14
    ["Pokemon/Routes/Yamper"] = 15
    ["Pokemon/Routes/Gyarados"] = 16
    ["Pokemon/Routes/Arrokuda"] = 17
    ["Pokemon/Routes/Barraskewda"] = 18
    ["Pokemon/Routes/Gossifleur"] = 19
    ["Pokemon/Routes/Machop"] = 20
    ["Pokemon/Routes/Klink"] = 21
    ["Pokemon/Routes/Pancham"] = 22
    ["Pokemon/Routes/Mudbray"] = 23
    ["Pokemon/Routes/Sizzlipede"] = 24
    ["Pokemon/Routes/Vulpix"] = 25
    ["Pokemon/Routes/Growlithe"] = 26
    ["Pokemon/Routes/Tyrogue"] = 27
    ["Pokemon/Routes/Stunky"] = 28
    ["Pokemon/Routes/Trubbish"] = 29
    ["Pokemon/Routes/Carkol"] = 30
    ["Pokemon/Routes/Rolycoly"] = 31
    ["Pokemon/Routes/Diglett"] = 32
    ["Pokemon/Routes/Roggenrola"] = 33
    ["Pokemon/Routes/Woobat"] = 34
    ["Pokemon/Routes/Drilbur"] = 35
    ["Pokemon/Routes/Timburr"] = 36
    ["Pokemon/Routes/Galarian Meowth"] = 37
    ["Pokemon/Routes/Budew"] = 38
    ["Pokemon/Routes/Joltik"] = 39
    ["Pokemon/Routes/Pikachu"] = 40
    ["Pokemon/Routes/Ferroseed"] = 41
    ["Pokemon/Routes/Cutiefly"] = 42
    ["Pokemon/Routes/Milcery"] = 43
    ["Pokemon/Routes/Eevee"] = 44
    ["Pokemon/Routes/Electrike"] = 45
    ["Pokemon/Routes/Pumpkaboo"] = 46
    ["Pokemon/Routes/Lombre"] = 47
    ["Pokemon/Routes/Nuzleaf"] = 48
    ["Pokemon/Routes/Nincada"] = 49
    ["Pokemon/Routes/Espurr"] = 50
    ["Pokemon/Routes/Spritzee"] = 51
    ["Pokemon/Routes/Swirlix"] = 52
    ["Pokemon/Routes/Dewpider"] = 53
    ["Pokemon/Routes/Dottler"] = 54
    ["Pokemon/Routes/Applin"] = 55
    ["Pokemon/Routes/Galarian Farfetch'd"] = 56
    ["Pokemon/Routes/Wobbuffet"] = 57
    ["Pokemon/Routes/Drifloon"] = 58
    ["Pokemon/Routes/Minccino"] = 59
    ["Pokemon/Routes/Stufful"] = 60
    ["Pokemon/Routes/Torkoal"] = 61
    ["Pokemon/Routes/Duskull"] = 62
    ["Pokemon/Routes/Hippopotas"] = 63
    ["Pokemon/Routes/Skorupi"] = 64
    ["Pokemon/Routes/Heatmor"] = 65
    ["Pokemon/Routes/Durant"] = 66
    ["Pokemon/Routes/Hawlucha"] = 67
    ["Pokemon/Routes/Silicobra"] = 68
    ["Pokemon/Routes/Dugtrio"] = 69
    ["Pokemon/Routes/Trapinch"] = 70
    ["Pokemon/Routes/Maractus"] = 71
    ["Pokemon/Routes/Galarian Yamask"] = 72
    ["Pokemon/Routes/Axew"] = 73
    ["Pokemon/Routes/Helioptile"] = 74
    ["Pokemon/Routes/Seismitoad"] = 75
    ["Pokemon/Routes/Karrablast"] = 76
    ["Pokemon/Routes/Shelmet"] = 77
    ["Pokemon/Routes/Meowstic"] = 78
    ["Pokemon/Routes/Corviknight"] = 79
    ["Pokemon/Routes/Toxel"] = 80
    ["Pokemon/Routes/Liepard"] = 81
    ["Pokemon/Routes/Galvantula"] = 82
    ["Pokemon/Routes/Inkay"] = 83
    ["Pokemon/Routes/Thievul"] = 84
    ["Pokemon/Routes/Perrserker"] = 85
    ["Pokemon/Routes/Morpeko"] = 86
    ["Pokemon/Routes/Haunter"] = 87
    ["Pokemon/Routes/Rhyhorn"] = 88
    ["Pokemon/Routes/Dusclops"] = 89
    ["Pokemon/Routes/Bronzong"] = 90
    ["Pokemon/Routes/Hippowdon"] = 91
    ["Pokemon/Routes/Drapion"] = 92
    ["Pokemon/Routes/Sandaconda"] = 93
    ["Pokemon/Routes/Falinks"] = 94
    ["Pokemon/Routes/Lunatone"] = 95
    ["Pokemon/Routes/Solrock"] = 96
    ["Pokemon/Routes/Boldore"] = 97
    ["Pokemon/Routes/Gurdurr"] = 98
    ["Pokemon/Routes/Golett"] = 99
    ["Pokemon/Routes/Pawniard"] = 100
    ["Pokemon/Routes/Vullaby"] = 101
    ["Pokemon/Routes/Rufflet"] = 102
    ["Pokemon/Routes/Togedemaru"] = 103
    ["Pokemon/Routes/Sneasel"] = 104
    ["Pokemon/Routes/Delibird"] = 105
    ["Pokemon/Routes/Snover"] = 106
    ["Pokemon/Routes/Galarian Darumaka"] = 107
    ["Pokemon/Routes/Snom"] = 108
    ["Pokemon/Routes/Snorunt"] = 109
    ["Pokemon/Routes/Throh"] = 110
    ["Pokemon/Routes/Sawk"] = 111
    ["Pokemon/Routes/Vanillish"] = 112
    ["Pokemon/Routes/Kingler"] = 113
    ["Pokemon/Routes/Octillery"] = 114
    ["Pokemon/Routes/Cramorant"] = 115
    ["Pokemon/Routes/Pincurchin"] = 116
    ["Pokemon/Routes/Pelipper"] = 117
    ["Pokemon/Routes/Gastrodon"] = 118
    ["Pokemon/Routes/Jellicent"] = 119
    ["Pokemon/Routes/Mareanie"] = 120
    ["Pokemon/Routes/Pyukumuku"] = 121
    ["Pokemon/Routes/Qwilfish"] = 122
    ["Pokemon/Routes/Mantyke"] = 123
    ["Pokemon/Routes/Bergmite"] = 124
    ["Pokemon/Routes/Dhelmise"] = 125
    ["Pokemon/Routes/Clobbopus"] = 126
    ["Pokemon/Routes/Toxapex"] = 127
    ["Pokemon/Routes/Grapploct"] = 128
    ["Trees/Berry Tree - Route 3"] = 129
    ["Trees/All/Berry Tree - Route 4"] = 130,
    ["Trees/All/Berry Tree - Route 5"] = 131,
    ["Trees/All/Berry Tree - Route 6"] = 132,
    ["Trees/All/Berry Tree 1 - Route 7"] = 133,
    ["Trees/All/Berry Tree 2 - Route 7"] = 134,
    ["Trees/All/Berry Tree 1 - Route 9"] = 135,
    ["Trees/All/Berry Tree 2 - Route 9"] = 136,
    ["Trees/All/Berry Tree - Axew's Eye"] = 137,
    ["Trees/All/Berry Tree 1 - Bridge Field"] = 138,
    ["Trees/All/Berry Tree 2 - Bridge Field"] = 139,
    ["Trees/All/Berry Tree 3 - Bridge Field"] = 140,
    ["Trees/All/Berry Tree 4 - Bridge Field"] = 141,
    ["Trees/All/Berry Tree 1 - Dappled Grove"] = 142,
    ["Trees/All/Berry Tree 2 - Dappled Grove"] = 143,
    ["Trees/All/Berry Tree 3 - Dappled Grove"] = 144,
    ["Trees/All/Berry Tree 4 - Dappled Grove"] = 145,
    ["Trees/All/Berry Tree 1 - Giant's Cap"] = 146,
    ["Trees/All/Berry Tree - Giant's Mirror"] = 147,
    ["Trees/All/Berry Tree - Giant's Seat"] = 148,
    ["Trees/All/Berry Tree 1 - Hammerlocke Hills"] = 149,
    ["Trees/All/Berry Tree 2 - Hammerlocke Hills"] = 150,
    ["Trees/All/Berry Tree - Lake of Outrage"] = 151,
    ["Trees/All/Berry Tree 1 - Motostoke Riverbank"] = 152,
    ["Trees/All/Berry Tree 2 - Motostoke Riverbank"] = 153,
    ["Trees/All/Berry Tree - North Lake Miloch"] = 154,
    ["Trees/All/Berry Tree 1 - Rolling Fields"] = 155,
    ["Trees/All/Berry Tree 2 - Rolling Fields"] = 156,
    ["Trees/All/Berry Tree - Watchtower Ruins"] = 157
    ["Dens/All/Axew's Eye - Den 1"] = 158,
    ["Dens/All/Rolling Fields - Den 1"] = 159,
    ["Dens/All/Rolling Fields - Den 2"] = 160,
    ["Dens/All/Rolling Fields - Den 3"] = 161,
    ["Dens/All/Rolling Fields - Den 4"] = 162,
    ["Dens/All/Rolling Fields - Den 5"] = 163,
    ["Dens/All/Rolling Fields - Den 6"] = 164,
    ["Dens/All/Rolling Fields - Den 7"] = 165,
    ["Dens/All/Rolling Fields - Den 8"] = 166,
    ["Dens/All/Rolling Fields - Den 9"] = 167,
    ["Dens/All/Dappled Grove - Den 1"] = 168,
    ["Dens/All/Dappled Grove - Den 2"] = 169,
    ["Dens/All/Dappled Grove - Den 3"] = 170,
    ["Dens/All/Dappled Grove - Den 4"] = 171,
    ["Dens/All/Dappled Grove - Den 5"] = 172,
    ["Dens/All/West Lake Axewell - Den 1"] = 173,
    ["Dens/All/West Lake Axewell - Den 2"] = 174,
    ["Dens/All/West Lake Axewell - Den 3"] = 175,
    ["Dens/All/West Lake Axewell - Den 4"] = 176,
    ["Dens/All/West Lake Axewell - Den 5"] = 177,
    ["Dens/All/West Lake Axewell - Den 6"] = 178,
    ["Dens/All/Watchtower Ruins - Den 1"] = 179,
    ["Dens/All/Watchtower Ruins - Den 2"] = 180,
    ["Dens/All/East Lake Axewell - Den 1"] = 181,
    ["Dens/All/East Lake Axewell - Den 2"] = 182,
    ["Dens/All/East Lake Axewell - Den 3"] = 183,
    ["Dens/All/East Lake Axewell - Den 4"] = 184,
    ["Dens/All/East Lake Axewell - Den 5"] = 185,
    ["Dens/All/North Lake Miloch - Den 1"] = 186,
    ["Dens/All/North Lake Miloch - Den 2"] = 187,
    ["Dens/All/North Lake Miloch - Den 3"] = 188,
    ["Dens/All/North Lake Miloch - Den 4"] = 189,
    ["Dens/All/North Lake Miloch - Den 5"] = 190,
    ["Dens/All/North Lake Miloch - Den 6"] = 191,
    ["Dens/All/Giant's Seat - Den 1"] = 192,
    ["Dens/All/Giant's Seat - Den 2"] = 193,
    ["Dens/All/Giant's Seat - Den 3"] = 194,
    ["Dens/All/Giant's Seat - Den 4"] = 195,
    ["Dens/All/Giant's Seat - Den 5"] = 196,
    ["Dens/All/South Lake Miloch - Den 1"] = 197,
    ["Dens/All/South Lake Miloch - Den 2"] = 198,
    ["Dens/All/South Lake Miloch - Den 3"] = 199,
    ["Dens/All/South Lake Miloch - Den 4"] = 200,
    ["Dens/All/South Lake Miloch - Den 5"] = 201,
    ["Dens/All/Motostoke Riverbank - Den 1"] = 202,
    ["Dens/All/Motostoke Riverbank - Den 2"] = 203,
    ["Dens/All/Motostoke Riverbank - Den 3"] = 204,
    ["Dens/All/Motostoke Riverbank - Den 4"] = 205,
    ["Dens/All/Bridge Field - Den 1"] = 206,
    ["Dens/All/Bridge Field - Den 2"] = 207,
    ["Dens/All/Bridge Field - Den 3"] = 208,
    ["Dens/All/Bridge Field - Den 4"] = 209,
    ["Dens/All/Bridge Field - Den 5"] = 210,
    ["Dens/All/Bridge Field - Den 6"] = 211,
    ["Dens/All/Bridge Field - Den 7"] = 212,
    ["Dens/All/Bridge Field - Den 8"] = 213,
    ["Dens/All/Bridge Field - Den 9"] = 214,
    ["Dens/All/Stony Wilderness - Den 1"] = 215,
    ["Dens/All/Stony Wilderness - Den 2"] = 216,
    ["Dens/All/Stony Wilderness - Den 3"] = 217,
    ["Dens/All/Stony Wilderness - Den 4"] = 218,
    ["Dens/All/Stony Wilderness - Den 5"] = 219,
    ["Dens/All/Stony Wilderness - Den 6"] = 220,
    ["Dens/All/Stony Wilderness - Den 7"] = 221,
    ["Dens/All/Stony Wilderness - Den 8"] = 222,
    ["Dens/All/Stony Wilderness - Den 9"] = 223,
    ["Dens/All/Stony Wilderness - Den 10"] = 224,
    ["Dens/All/Stony Wilderness - Den 11"] = 225,
    ["Dens/All/Stony Wilderness - Den 12"] = 226,
    ["Dens/All/Giant's Mirror - Den 1"] = 227,
    ["Dens/All/Giant's Mirror - Den 2"] = 228,
    ["Dens/All/Giant's Mirror - Den 3"] = 229,
    ["Dens/All/Giant's Mirror - Den 4"] = 230,
    ["Dens/All/Giant's Mirror - Den 5"] = 231,
    ["Dens/All/Dusty Bowl - Den 1"] = 232,
    ["Dens/All/Dusty Bowl - Den 2"] = 233,
    ["Dens/All/Dusty Bowl - Den 3"] = 234,
    ["Dens/All/Dusty Bowl - Den 4"] = 235,
    ["Dens/All/Dusty Bowl - Den 5"] = 236,
    ["Dens/All/Dusty Bowl - Den 6"] = 237,
    ["Dens/All/Dusty Bowl - Den 7"] = 238,
    ["Dens/All/Dusty Bowl - Den 8"] = 239,
    ["Dens/All/Dusty Bowl - Den 9"] = 240,
    ["Dens/All/Hammerlocke Hills - Den 1"] = 241,
    ["Dens/All/Hammerlocke Hills - Den 2"] = 242,
    ["Dens/All/Hammerlocke Hills - Den 3"] = 243,
    ["Dens/All/Hammerlocke Hills - Den 4"] = 244,
    ["Dens/All/Hammerlocke Hills - Den 5"] = 245,
    ["Dens/All/Hammerlocke Hills - Den 6"] = 246,
    ["Dens/All/Hammerlocke Hills - Den 7"] = 247,
    ["Dens/All/Giant's Cap - Den 1"] = 248,
    ["Dens/All/Giant's Cap - Den 2"] = 249,
    ["Dens/All/Giant's Cap - Den 3"] = 250,
    ["Dens/All/Giant's Cap - Den 4"] = 251,
    ["Dens/All/Giant's Cap - Den 5"] = 252,
    ["Dens/All/Lake of Outrage - Den 1"] = 253,
    ["Dens/All/Lake of Outrage - Den 2"] = 254,
    ["Dens/All/Lake of Outrage - Den 3"] = 255,
    ["Dens/All/Lake of Outrage - Den 4"] = 256
    ["Pokemon/Wanderer/Wanderer Abomasnow"] = 257,
    ["Pokemon/Wanderer/Wanderer Aegislash"] = 258,
    ["Pokemon/Wanderer/Wanderer Araquanid"] = 259,
    ["Pokemon/Wanderer/Wanderer Avalugg"] = 260,
    ["Pokemon/Wanderer/Wanderer Barbaracle"] = 261,
    ["Pokemon/Wanderer/Wanderer Beartic"] = 262,
    ["Pokemon/Wanderer/Wanderer Beheeyem"] = 263,
    ["Pokemon/Wanderer/Wanderer Bellossom"] = 264,
    ["Pokemon/Wanderer/Wanderer Bewear"] = 265,
    ["Pokemon/Wanderer/Wanderer Bisharp"] = 266,
    ["Pokemon/Wanderer/Wanderer Boltund"] = 267,
    ["Pokemon/Wanderer/Wanderer Bronzong"] = 268,
    ["Pokemon/Wanderer/Wanderer Chandelure"] = 269,
    ["Pokemon/Wanderer/Wanderer Cinccino"] = 270,
    ["Pokemon/Wanderer/Wanderer Claydol"] = 271,
    ["Pokemon/Wanderer/Wanderer Clefable"] = 272,
    ["Pokemon/Wanderer/Wanderer Coalossal"] = 273,
    ["Pokemon/Wanderer/Wanderer Conkeldurr"] = 274,
    ["Pokemon/Wanderer/Wanderer Copperajah"] = 275,
    ["Pokemon/Wanderer/Wanderer Corviknight"] = 276,
    ["Pokemon/Wanderer/Wanderer Cramorant"] = 277,
    ["Pokemon/Wanderer/Wanderer Crawdaunt"] = 278,
    ["Pokemon/Wanderer/Wanderer Crustle"] = 279,
    ["Pokemon/Wanderer/Wanderer Diggersby"] = 280,
    ["Pokemon/Wanderer/Wanderer Doublade"] = 281,
    ["Pokemon/Wanderer/Wanderer Drapion"] = 282,
    ["Pokemon/Wanderer/Wanderer Drednaw"] = 283,
    ["Pokemon/Wanderer/Wanderer Drifblim"] = 284,
    ["Pokemon/Wanderer/Wanderer Dubwool"] = 285,
    ["Pokemon/Wanderer/Wanderer Duraludon"] = 286,
    ["Pokemon/Wanderer/Wanderer Dusclops"] = 287,
    ["Pokemon/Wanderer/Wanderer Dusknoir"] = 288,
    ["Pokemon/Wanderer/Wanderer Eldegoss"] = 289,
    ["Pokemon/Wanderer/Wanderer Espeon"] = 290,
    ["Pokemon/Wanderer/Wanderer Excadrill"] = 291,
    ["Pokemon/Wanderer/Wanderer Ferrothorn"] = 292,
    ["Pokemon/Wanderer/Wanderer Flareon"] = 293,
    ["Pokemon/Wanderer/Wanderer Flygon"] = 294,
    ["Pokemon/Wanderer/Wanderer Galarian Weezing"] = 295,
    ["Pokemon/Wanderer/Wanderer Gallade"] = 296,
    ["Pokemon/Wanderer/Wanderer Galvantula"] = 297,
    ["Pokemon/Wanderer/Wanderer Garbodor"] = 298,
    ["Pokemon/Wanderer/Wanderer Gardevoir"] = 299,
    ["Pokemon/Wanderer/Wanderer Gengar"] = 300,
    ["Pokemon/Wanderer/Wanderer Gigalith"] = 301,
    ["Pokemon/Wanderer/Wanderer Glaceon"] = 302,
    ["Pokemon/Wanderer/Wanderer Glalie"] = 303,
    ["Pokemon/Wanderer/Wanderer Golisopod"] = 304,
    ["Pokemon/Wanderer/Wanderer Golurk"] = 305,
    ["Pokemon/Wanderer/Wanderer Gourgeist"] = 306,
    ["Pokemon/Wanderer/Wanderer Grapploct"] = 307,
    ["Pokemon/Wanderer/Wanderer Greedent"] = 308,
    ["Pokemon/Wanderer/Wanderer Grimmsnarl"] = 309,
    ["Pokemon/Wanderer/Wanderer Hatterene"] = 310,
    ["Pokemon/Wanderer/Wanderer Haunter"] = 311,
    ["Pokemon/Wanderer/Wanderer Hawlucha"] = 312,
    ["Pokemon/Wanderer/Wanderer Haxorus"] = 313,
    ["Pokemon/Wanderer/Wanderer Jolteon"] = 314,
    ["Pokemon/Wanderer/Wanderer Kingler"] = 315,
    ["Pokemon/Wanderer/Wanderer Kirlia"] = 316,
    ["Pokemon/Wanderer/Wanderer Klang"] = 317,
    ["Pokemon/Wanderer/Wanderer Klinklang"] = 318,
    ["Pokemon/Wanderer/Wanderer Tyranitar"] = 319,
    ["Pokemon/Wanderer/Wanderer Kommo-o"] = 320,
    ["Pokemon/Wanderer/Wanderer Leafeon"] = 321,
    ["Pokemon/Wanderer/Wanderer Liepard"] = 322
    ["Pokemon/Wanderer/Wanderer Linoone"] = 323,
    ["Pokemon/Wanderer/Wanderer Lucario"] = 324,
    ["Pokemon/Wanderer/Wanderer Ludicolo"] = 325,
    ["Pokemon/Wanderer/Wanderer Machamp"] = 326,
    ["Pokemon/Wanderer/Wanderer Machoke"] = 327,
    ["Pokemon/Wanderer/Wanderer Manectric"] = 328,
    ["Pokemon/Wanderer/Wanderer Mime Jr."] = 329,
    ["Pokemon/Wanderer/Wanderer Mimikyu"] = 330,
    ["Pokemon/Wanderer/Wanderer Mudsdale"] = 331,
    ["Pokemon/Wanderer/Wanderer Musharna"] = 332,
    ["Pokemon/Wanderer/Wanderer Ninjask"] = 333,
    ["Pokemon/Wanderer/Wanderer Noctowl"] = 334,
    ["Pokemon/Wanderer/Wanderer Noivern"] = 335,
    ["Pokemon/Wanderer/Wanderer Obstagoon"] = 336,
    ["Pokemon/Wanderer/Wanderer Onix"] = 337,
    ["Pokemon/Wanderer/Wanderer Orbeetle"] = 338,
    ["Pokemon/Wanderer/Wanderer Palpitoad"] = 339,
    ["Pokemon/Wanderer/Wanderer Pangoro"] = 340,
    ["Pokemon/Wanderer/Wanderer Pelipper"] = 341,
    ["Pokemon/Wanderer/Wanderer Perrserker"] = 342,
    ["Pokemon/Wanderer/Wanderer Pikachu"] = 343,
    ["Pokemon/Wanderer/Wanderer Piloswine"] = 344,
    ["Pokemon/Wanderer/Wanderer Quagsire"] = 345,
    ["Pokemon/Wanderer/Wanderer Rhydon"] = 346,
    ["Pokemon/Wanderer/Wanderer Ribombee"] = 347,
    ["Pokemon/Wanderer/Wanderer Roselia"] = 348,
    ["Pokemon/Wanderer/Wanderer Roserade"] = 349,
    ["Pokemon/Wanderer/Wanderer Sandaconda"] = 350,
    ["Pokemon/Wanderer/Wanderer Seismitoad"] = 351,
    ["Pokemon/Wanderer/Wanderer Shiftry"] = 352,
    ["Pokemon/Wanderer/Wanderer Shiinotic"] = 353,
    ["Pokemon/Wanderer/Wanderer Shuckle"] = 354,
    ["Pokemon/Wanderer/Wanderer Sigilyph"] = 355,
    ["Pokemon/Wanderer/Wanderer Skuntank"] = 356,
    ["Pokemon/Wanderer/Wanderer Snorlax"] = 357,
    ["Pokemon/Wanderer/Wanderer Steelix"] = 358,
    ["Pokemon/Wanderer/Wanderer Sudowoodo"] = 359,
    ["Pokemon/Wanderer/Wanderer Sylveon"] = 360,
    ["Pokemon/Wanderer/Wanderer Thievul"] = 361,
    ["Pokemon/Wanderer/Wanderer Tsareena"] = 362,
    ["Pokemon/Wanderer/Wanderer Umbreon"] = 363,
    ["Pokemon/Wanderer/Wanderer Unfezant"] = 364,
    ["Pokemon/Wanderer/Wanderer Vanillish"] = 365,
    ["Pokemon/Wanderer/Wanderer Vanilluxe"] = 366,
    ["Pokemon/Wanderer/Wanderer Vaporeon"] = 367,
    ["Pokemon/Wanderer/Wanderer Vespiquen"] = 368,
    ["Pokemon/Wanderer/Wanderer Vikavolt"] = 369,
    ["Pokemon/Wanderer/Wanderer Vileplume"] = 370,
    ["Pokemon/Wanderer/Wanderer Weavile"] = 371,
    ["Pokemon/Wanderer/Wanderer Xatu"] = 372,
    ["Pokemon/Wanderer/Wanderer Seaking"] = 373,
    ["Pokemon/Wanderer/Wanderer Lanturn"] = 374,
    ["Pokemon/Wanderer/Wanderer Gyarados"] = 375,
    ["Pokemon/Wanderer/Wanderer Gastrodon"] = 376,
    ["Pokemon/Wanderer/Wanderer Jellicent"] = 377,
    ["Pokemon/Wanderer/Wanderer Cloyster"] = 378,
    ["Pokemon/Wanderer/Wanderer Milotic"] = 379,
    ["Pokemon/Wanderer/Wanderer Lapras"] = 380,
    ["Pokemon/Wanderer/Wanderer Wailmer"] = 381,
    ["Pokemon/Wanderer/Wanderer Whiscash"] = 382,
    ["Pokemon/Wanderer/Wanderer Octillery"] = 383,
    ["Pokemon/Routes/Rhydon"] = 384
    ["Pokemon/Routes/Klang"] = 385
    ["Pokemon/Routes/Galarian Mr. Mime"] = 386
    ["Pokemon/Routes/Glalie"] = 387
    ["Pokemon/Routes/Vanilluxe"] = 388
    ["Pokemon/Routes/Cubchoo"] = 389
    ["Pokemon/Routes/Abomasnow"] = 390
    ["Pokemon/Routes/Beartic"] = 391
    ["Pokemon/Routes/Stonjourner"] = 392
    ["Pokemon/Routes/Eiscue"] = 393
    ["Pokemon/Routes/Duraludon"] = 394
    ["Pokemon/Routes/Shuckle"] = 395
    ["Pokemon/Routes/Shellos"] = 396
    ["Pokemon/Routes/Croagunk"] = 397
    ["Pokemon/Routes/Scraggy"] = 398
    ["Pokemon/Routes/Binacle"] = 399
    ["Pokemon/Routes/Noibat"] = 400
    ["Pokemon/Routes/Wimpod"] = 401
    ["Pokemon/Routes/Butterfree"] = 402
    ["Pokemon/Routes/Galarian Weezing"] = 403
    ["Pokemon/Routes/Munna"] = 404
    ["Pokemon/Routes/Orbeetle"] = 405
    ["Pokemon/Routes/Galarian Stunfisk"] = 406
    ["Pokemon/Routes/Impidimp"] = 407
    ["Pokemon/Routes/Koffing"] = 408
    ["Pokemon/Routes/Noctowl"] = 409
    ["Pokemon/Routes/Sudowoodo"] = 410
    ["Pokemon/Routes/Salandit"] = 411
    ["Pokemon/Routes/Hatenna"] = 412
    ["Pokemon/Routes/Galarian Ponyta"] = 413
    ["Pokemon/Routes/Phantump"] = 414
    ["Pokemon/Routes/Shiinotic"] = 415
    ["Pokemon/Routes/Oranguru"] = 416
    ["Pokemon/Routes/Passimian"] = 417
    ["Pokemon/Routes/Sinistea"] = 418
    ["Pokemon/Routes/Hattrem"] = 419
    ["Pokemon/Routes/Morgrem"] = 420
    ["Pokemon/Routes/Indeedee"] = 421
}
ID_TO_LOCATION_MAP = {
    [1] = {"@Win Condition/All/Eternatus"},
    [2] = {"@Pokemon/Routes/Blipbug"},
    [3] = {"@Pokemon/Routes/Caterpie"},
    [4] = {"@Pokemon/Routes/Grubbin"},
    [5] = {"@Pokemon/Routes/Hoothoot"},
    [6] = {"@Pokemon/Routes/Nickit"},
    [7] = {"@Pokemon/Routes/Rookidee"},
    [8] = {"@Pokemon/Routes/Skwovet"},
    [9] = {"@Pokemon/Routes/Wooloo"},
    [10] = {"@Pokemon/Routes/Lotad"},
    [11] = {"@Pokemon/Routes/Seedot"},
    [12] = {"@Pokemon/Routes/Purrloin"},
    [13] = {"@Pokemon/Routes/Galarian Zigzagoon"},
    [14] = {"@Pokemon/Routes/Chewtle"},
    [15] = {"@Pokemon/Routes/Yamper"},
    [16] = {"@Pokemon/Routes/Gyarados"},
    [17] = {"@Pokemon/Routes/Arrokuda"},
    [18] = {"@Pokemon/Routes/Barraskewda"},
    [19] = {"@Pokemon/Routes/Gossifleur"},
    [20] = {"@Pokemon/Routes/Machop"},
    [21] = {"@Pokemon/Routes/Klink"},
    [22] = {"@Pokemon/Routes/Pancham"},
    [23] = {"@Pokemon/Routes/Mudbray"},
    [24] = {"@Pokemon/Routes/Sizzlipede"},
    [25] = {"@Pokemon/Routes/Vulpix"},
    [26] = {"@Pokemon/Routes/Growlithe"},
    [27] = {"@Pokemon/Routes/Tyrogue"},
    [28] = {"@Pokemon/Routes/Stunky"},
    [29] = {"@Pokemon/Routes/Trubbish"},
    [30] = {"@Pokemon/Routes/Carkol"},
    [31] = {"@Pokemon/Routes/Rolycoly"},
    [32] = {"@Pokemon/Routes/Diglett"},
    [33] = {"@Pokemon/Routes/Roggenrola"},
    [34] = {"@Pokemon/Routes/Woobat"},
    [35] = {"@Pokemon/Routes/Drilbur"},
    [36] = {"@Pokemon/Routes/Timburr"},
    [37] = {"@Pokemon/Routes/Galarian Meowth"},
    [38] = {"@Pokemon/Routes/Budew"},
    [39] = {"@Pokemon/Routes/Joltik"},
    [40] = {"@Pokemon/Routes/Pikachu"},
    [41] = {"@Pokemon/Routes/Ferroseed"},
    [42] = {"@Pokemon/Routes/Cutiefly"},
    [43] = {"@Pokemon/Routes/Milcery"},
    [44] = {"@Pokemon/Routes/Eevee"},
    [45] = {"@Pokemon/Routes/Electrike"},
    [46] = {"@Pokemon/Routes/Pumpkaboo"},
    [47] = {"@Pokemon/Routes/Lombre"},
    [48] = {"@Pokemon/Routes/Nuzleaf"},
    [49] = {"@Pokemon/Routes/Nincada"},
    [50] = {"@Pokemon/Routes/Espurr"},
    [51] = {"@Pokemon/Routes/Spritzee"},
    [52] = {"@Pokemon/Routes/Swirlix"},
    [53] = {"@Pokemon/Routes/Dewpider"},
    [54] = {"@Pokemon/Routes/Dottler"},
    [55] = {"@Pokemon/Routes/Applin"},
    [56] = {"@Pokemon/Routes/Galarian Farfetch'd"},
    [57] = {"@Pokemon/Routes/Wobbuffet"},
    [58] = {"@Pokemon/Routes/Drifloon"},
    [59] = {"@Pokemon/Routes/Minccino"},
    [60] = {"@Pokemon/Routes/Stufful"},
    [61] = {"@Pokemon/Routes/Torkoal"},
    [62] = {"@Pokemon/Routes/Duskull"},
    [63] = {"@Pokemon/Routes/Hippopotas"},
    [64] = {"@Pokemon/Routes/Skorupi"},
    [65] = {"@Pokemon/Routes/Heatmor"},
    [66] = {"@Pokemon/Routes/Durant"},
    [67] = {"@Pokemon/Routes/Hawlucha"},
    [68] = {"@Pokemon/Routes/Silicobra"},
    [69] = {"@Pokemon/Routes/Dugtrio"},
    [70] = {"@Pokemon/Routes/Trapinch"},
    [71] = {"@Pokemon/Routes/Maractus"},
    [72] = {"@Pokemon/Routes/Galarian Yamask"},
    [73] = {"@Pokemon/Routes/Axew"},
    [74] = {"@Pokemon/Routes/Helioptile"},
    [75] = {"@Pokemon/Routes/Seismitoad"},
    [76] = {"@Pokemon/Routes/Karrablast"},
    [77] = {"@Pokemon/Routes/Shelmet"},
    [78] = {"@Pokemon/Routes/Meowstic"},
    [79] = {"@Pokemon/Routes/Corviknight"},
    [80] = {"@Pokemon/Routes/Toxel"},
    [81] = {"@Pokemon/Routes/Liepard"},
    [82] = {"@Pokemon/Routes/Galvantula"},
    [83] = {"@Pokemon/Routes/Inkay"},
    [84] = {"@Pokemon/Routes/Thievul"},
    [85] = {"@Pokemon/Routes/Perrserker"},
    [86] = {"@Pokemon/Routes/Morpeko"},
    [87] = {"@Pokemon/Routes/Haunter"},
    [88] = {"@Pokemon/Routes/Rhyhorn"},
    [89] = {"@Pokemon/Routes/Dusclops"},
    [90] = {"@Pokemon/Routes/Bronzong"},
    [91] = {"@Pokemon/Routes/Hippowdon"},
    [92] = {"@Pokemon/Routes/Drapion"},
    [93] = {"@Pokemon/Routes/Sandaconda"},
    [94] = {"@Pokemon/Routes/Falinks"},
    [95] = {"@Pokemon/Routes/Lunatone"},
    [96] = {"@Pokemon/Routes/Solrock"},
    [97] = {"@Pokemon/Routes/Boldore"},
    [98] = {"@Pokemon/Routes/Gurdurr"},
    [99] = {"@Pokemon/Routes/Golett"},
    [100] = {"@Pokemon/Routes/Pawniard"},
    [101] = {"@Pokemon/Routes/Vullaby"},
    [102] = {"@Pokemon/Routes/Rufflet"},
    [103] = {"@Pokemon/Routes/Togedemaru"},
    [104] = {"@Pokemon/Routes/Sneasel"},
    [105] = {"@Pokemon/Routes/Delibird"},
    [106] = {"@Pokemon/Routes/Snover"},
    [107] = {"@Pokemon/Routes/Galarian Darumaka"},
    [108] = {"@Pokemon/Routes/Snom"},
    [109] = {"@Pokemon/Routes/Snorunt"},
    [110] = {"@Pokemon/Routes/Throh"},
    [111] = {"@Pokemon/Routes/Sawk"},
    [112] = {"@Pokemon/Routes/Vanillish"},
    [113] = {"@Pokemon/Routes/Kingler"},
    [114] = {"@Pokemon/Routes/Octillery"},
    [115] = {"@Pokemon/Routes/Cramorant"},
    [116] = {"@Pokemon/Routes/Pincurchin"},
    [117] = {"@Pokemon/Routes/Pelipper"},
    [118] = {"@Pokemon/Routes/Gastrodon"},
    [119] = {"@Pokemon/Routes/Jellicent"},
    [120] = {"@Pokemon/Routes/Mareanie"},
    [121] = {"@Pokemon/Routes/Pyukumuku"},
    [122] = {"@Pokemon/Routes/Qwilfish"},
    [123] = {"@Pokemon/Routes/Mantyke"},
    [124] = {"@Pokemon/Routes/Bergmite"},
    [125] = {"@Pokemon/Routes/Dhelmise"},
    [126] = {"@Pokemon/Routes/Clobbopus"},
    [127] = {"@Pokemon/Routes/Toxapex"},
    [128] = {"@Pokemon/Routes/Grapploct"},
    [129] = {"@Trees/All/Berry Tree - Route 3"}
    [130] = {"@Trees/All/Berry Tree - Route 4"},
    [131] = {"@Trees/All/Berry Tree - Route 5"},
    [132] = {"@Trees/All/Berry Tree - Route 6"},
    [133] = {"@Trees/All/Berry Tree 1 - Route 7"},
    [134] = {"@Trees/All/Berry Tree 2 - Route 7"},
    [135] = {"@Trees/All/Berry Tree 1 - Route 9"},
    [136] = {"@Trees/All/Berry Tree 2 - Route 9"},
    [137] = {"@Trees/All/Berry Tree - Axew's Eye"},
    [138] = {"@Trees/All/Berry Tree 1 - Bridge Field"},
    [139] = {"@Trees/All/Berry Tree 2 - Bridge Field"},
    [140] = {"@Trees/All/Berry Tree 3 - Bridge Field"},
    [141] = {"@Trees/All/Berry Tree 4 - Bridge Field"},
    [142] = {"@Trees/All/Berry Tree 1 - Dappled Grove"},
    [143] = {"@Trees/All/Berry Tree 2 - Dappled Grove"},
    [144] = {"@Trees/All/Berry Tree 3 - Dappled Grove"},
    [145] = {"@Trees/All/Berry Tree 4 - Dappled Grove"},
    [146] = {"@Trees/All/Berry Tree 1 - Giant's Cap"},
    [147] = {"@Trees/All/Berry Tree - Giant's Mirror"},
    [148] = {"@Trees/All/Berry Tree - Giant's Seat"},
    [149] = {"@Trees/All/Berry Tree 1 - Hammerlocke Hills"},
    [150] = {"@Trees/All/Berry Tree 2 - Hammerlocke Hills"},
    [151] = {"@Trees/All/Berry Tree - Lake of Outrage"},
    [152] = {"@Trees/All/Berry Tree 1 - Motostoke Riverbank"},
    [153] = {"@Trees/All/Berry Tree 2 - Motostoke Riverbank"},
    [154] = {"@Trees/All/Berry Tree - North Lake Miloch"},
    [155] = {"@Trees/All/Berry Tree 1 - Rolling Fields"},
    [156] = {"@Trees/All/Berry Tree 2 - Rolling Fields"},
    [157] = {"@Trees/All/Berry Tree - Watchtower Ruins"},
    [158] = {"@Dens/All/Axew's Eye - Den 1"},
    [159] = {"@Dens/All/Rolling Fields - Den 1"},
    [160] = {"@Dens/All/Rolling Fields - Den 2"},
    [161] = {"@Dens/All/Rolling Fields - Den 3"},
    [162] = {"@Dens/All/Rolling Fields - Den 4"},
    [163] = {"@Dens/All/Rolling Fields - Den 5"},
    [164] = {"@Dens/All/Rolling Fields - Den 6"},
    [165] = {"@Dens/All/Rolling Fields - Den 7"},
    [166] = {"@Dens/All/Rolling Fields - Den 8"},
    [167] = {"@Dens/All/Rolling Fields - Den 9"},
    [168] = {"@Dens/All/Dappled Grove - Den 1"},
    [169] = {"@Dens/All/Dappled Grove - Den 2"},
    [170] = {"@Dens/All/Dappled Grove - Den 3"},
    [171] = {"@Dens/All/Dappled Grove - Den 4"},
    [172] = {"@Dens/All/Dappled Grove - Den 5"},
    [173] = {"@Dens/All/West Lake Axewell - Den 1"},
    [174] = {"@Dens/All/West Lake Axewell - Den 2"},
    [175] = {"@Dens/All/West Lake Axewell - Den 3"},
    [176] = {"@Dens/All/West Lake Axewell - Den 4"},
    [177] = {"@Dens/All/West Lake Axewell - Den 5"},
    [178] = {"@Dens/All/West Lake Axewell - Den 6"},
    [179] = {"@Dens/All/Watchtower Ruins - Den 1"},
    [180] = {"@Dens/All/Watchtower Ruins - Den 2"},
    [181] = {"@Dens/All/East Lake Axewell - Den 1"},
    [182] = {"@Dens/All/East Lake Axewell - Den 2"},
    [183] = {"@Dens/All/East Lake Axewell - Den 3"},
    [184] = {"@Dens/All/East Lake Axewell - Den 4"},
    [185] = {"@Dens/All/East Lake Axewell - Den 5"},
    [186] = {"@Dens/All/North Lake Miloch - Den 1"},
    [187] = {"@Dens/All/North Lake Miloch - Den 2"},
    [188] = {"@Dens/All/North Lake Miloch - Den 3"},
    [189] = {"@Dens/All/North Lake Miloch - Den 4"},
    [190] = {"@Dens/All/North Lake Miloch - Den 5"},
    [191] = {"@Dens/All/North Lake Miloch - Den 6"},
    [192] = {"@Dens/All/Giant's Seat - Den 1"},
    [193] = {"@Dens/All/Giant's Seat - Den 2"},
    [194] = {"@Dens/All/Giant's Seat - Den 3"},
    [195] = {"@Dens/All/Giant's Seat - Den 4"},
    [196] = {"@Dens/All/Giant's Seat - Den 5"},
    [197] = {"@Dens/All/South Lake Miloch - Den 1"},
    [198] = {"@Dens/All/South Lake Miloch - Den 2"},
    [199] = {"@Dens/All/South Lake Miloch - Den 3"},
    [200] = {"@Dens/All/South Lake Miloch - Den 4"},
    [201] = {"@Dens/All/South Lake Miloch - Den 5"},
    [202] = {"@Dens/All/Motostoke Riverbank - Den 1"},
    [203] = {"@Dens/All/Motostoke Riverbank - Den 2"},
    [204] = {"@Dens/All/Motostoke Riverbank - Den 3"},
    [205] = {"@Dens/All/Motostoke Riverbank - Den 4"},
    [206] = {"@Dens/All/Bridge Field - Den 1"},
    [207] = {"@Dens/All/Bridge Field - Den 2"},
    [208] = {"@Dens/All/Bridge Field - Den 3"},
    [209] = {"@Dens/All/Bridge Field - Den 4"},
    [210] = {"@Dens/All/Bridge Field - Den 5"},
    [211] = {"@Dens/All/Bridge Field - Den 6"},
    [212] = {"@Dens/All/Bridge Field - Den 7"},
    [213] = {"@Dens/All/Bridge Field - Den 8"},
    [214] = {"@Dens/All/Bridge Field - Den 9"},
    [215] = {"@Dens/All/Stony Wilderness - Den 1"},
    [216] = {"@Dens/All/Stony Wilderness - Den 2"},
    [217] = {"@Dens/All/Stony Wilderness - Den 3"},
    [218] = {"@Dens/All/Stony Wilderness - Den 4"},
    [219] = {"@Dens/All/Stony Wilderness - Den 5"},
    [220] = {"@Dens/All/Stony Wilderness - Den 6"},
    [221] = {"@Dens/All/Stony Wilderness - Den 7"},
    [222] = {"@Dens/All/Stony Wilderness - Den 8"},
    [223] = {"@Dens/All/Stony Wilderness - Den 9"},
    [224] = {"@Dens/All/Stony Wilderness - Den 10"},
    [225] = {"@Dens/All/Stony Wilderness - Den 11"},
    [226] = {"@Dens/All/Stony Wilderness - Den 12"},
    [227] = {"@Dens/All/Giant's Mirror - Den 1"},
    [228] = {"@Dens/All/Giant's Mirror - Den 2"},
    [229] = {"@Dens/All/Giant's Mirror - Den 3"},
    [230] = {"@Dens/All/Giant's Mirror - Den 4"},
    [231] = {"@Dens/All/Giant's Mirror - Den 5"},
    [232] = {"@Dens/All/Dusty Bowl - Den 1"},
    [233] = {"@Dens/All/Dusty Bowl - Den 2"},
    [234] = {"@Dens/All/Dusty Bowl - Den 3"},
    [235] = {"@Dens/All/Dusty Bowl - Den 4"},
    [236] = {"@Dens/All/Dusty Bowl - Den 5"},
    [237] = {"@Dens/All/Dusty Bowl - Den 6"},
    [238] = {"@Dens/All/Dusty Bowl - Den 7"},
    [239] = {"@Dens/All/Dusty Bowl - Den 8"},
    [240] = {"@Dens/All/Dusty Bowl - Den 9"},
    [241] = {"@Dens/All/Hammerlocke Hills - Den 1"},
    [242] = {"@Dens/All/Hammerlocke Hills - Den 2"},
    [243] = {"@Dens/All/Hammerlocke Hills - Den 3"},
    [244] = {"@Dens/All/Hammerlocke Hills - Den 4"},
    [245] = {"@Dens/All/Hammerlocke Hills - Den 5"},
    [246] = {"@Dens/All/Hammerlocke Hills - Den 6"},
    [247] = {"@Dens/All/Hammerlocke Hills - Den 7"},
    [248] = {"@Dens/All/Giant's Cap - Den 1"},
    [249] = {"@Dens/All/Giant's Cap - Den 2"},
    [250] = {"@Dens/All/Giant's Cap - Den 3"},
    [251] = {"@Dens/All/Giant's Cap - Den 4"},
    [252] = {"@Dens/All/Giant's Cap - Den 5"},
    [253] = {"@Dens/All/Lake of Outrage - Den 1"},
    [254] = {"@Dens/All/Lake of Outrage - Den 2"},
    [255] = {"@Dens/All/Lake of Outrage - Den 3"},
    [256] = {"@Dens/All/Lake of Outrage - Den 4"},
    [257] = {"@Pokemon/Wanderer/Wanderer Abomasnow"},
    [258] = {"@Pokemon/Wanderer/Wanderer Aegislash"},
    [259] = {"@Pokemon/Wanderer/Wanderer Araquanid"},
    [260] = {"@Pokemon/Wanderer/Wanderer Avalugg"},
    [261] = {"@Pokemon/Wanderer/Wanderer Barbaracle"},
    [262] = {"@Pokemon/Wanderer/Wanderer Beartic"},
    [263] = {"@Pokemon/Wanderer/Wanderer Beheeyem"},
    [264] = {"@Pokemon/Wanderer/Wanderer Bellossom"},
    [265] = {"@Pokemon/Wanderer/Wanderer Bewear"},
    [266] = {"@Pokemon/Wanderer/Wanderer Bisharp"},
    [267] = {"@Pokemon/Wanderer/Wanderer Boltund"},
    [268] = {"@Pokemon/Wanderer/Wanderer Bronzong"},
    [269] = {"@Pokemon/Wanderer/Wanderer Chandelure"},
    [270] = {"@Pokemon/Wanderer/Wanderer Cinccino"},
    [271] = {"@Pokemon/Wanderer/Wanderer Claydol"},
    [272] = {"@Pokemon/Wanderer/Wanderer Clefable"},
    [273] = {"@Pokemon/Wanderer/Wanderer Coalossal"},
    [274] = {"@Pokemon/Wanderer/Wanderer Conkeldurr"},
    [275] = {"@Pokemon/Wanderer/Wanderer Copperajah"},
    [276] = {"@Pokemon/Wanderer/Wanderer Corviknight"},
    [277] = {"@Pokemon/Wanderer/Wanderer Cramorant"},
    [278] = {"@Pokemon/Wanderer/Wanderer Crawdaunt"},
    [279] = {"@Pokemon/Wanderer/Wanderer Crustle"},
    [280] = {"@Pokemon/Wanderer/Wanderer Diggersby"},
    [281] = {"@Pokemon/Wanderer/Wanderer Doublade"},
    [282] = {"@Pokemon/Wanderer/Wanderer Drapion"},
    [283] = {"@Pokemon/Wanderer/Wanderer Drednaw"},
    [284] = {"@Pokemon/Wanderer/Wanderer Drifblim"},
    [285] = {"@Pokemon/Wanderer/Wanderer Dubwool"},
    [286] = {"@Pokemon/Wanderer/Wanderer Duraludon"},
    [287] = {"@Pokemon/Wanderer/Wanderer Dusclops"},
    [288] = {"@Pokemon/Wanderer/Wanderer Dusknoir"},
    [289] = {"@Pokemon/Wanderer/Wanderer Eldegoss"},
    [290] = {"@Pokemon/Wanderer/Wanderer Espeon"},
    [291] = {"@Pokemon/Wanderer/Wanderer Excadrill"},
    [292] = {"@Pokemon/Wanderer/Wanderer Ferrothorn"},
    [293] = {"@Pokemon/Wanderer/Wanderer Flareon"},
    [294] = {"@Pokemon/Wanderer/Wanderer Flygon"},
    [295] = {"@Pokemon/Wanderer/Wanderer Galarian Weezing"},
    [296] = {"@Pokemon/Wanderer/Wanderer Gallade"},
    [297] = {"@Pokemon/Wanderer/Wanderer Galvantula"},
    [298] = {"@Pokemon/Wanderer/Wanderer Garbodor"},
    [299] = {"@Pokemon/Wanderer/Wanderer Gardevoir"},
    [300] = {"@Pokemon/Wanderer/Wanderer Gengar"},
    [301] = {"@Pokemon/Wanderer/Wanderer Gigalith"},
    [302] = {"@Pokemon/Wanderer/Wanderer Glaceon"},
    [303] = {"@Pokemon/Wanderer/Wanderer Glalie"},
    [304] = {"@Pokemon/Wanderer/Wanderer Golisopod"},
    [305] = {"@Pokemon/Wanderer/Wanderer Golurk"},
    [306] = {"@Pokemon/Wanderer/Wanderer Gourgeist"},
    [307] = {"@Pokemon/Wanderer/Wanderer Grapploct"},
    [308] = {"@Pokemon/Wanderer/Wanderer Greedent"},
    [309] = {"@Pokemon/Wanderer/Wanderer Grimmsnarl"},
    [310] = {"@Pokemon/Wanderer/Wanderer Hatterene"},
    [311] = {"@Pokemon/Wanderer/Wanderer Haunter"},
    [312] = {"@Pokemon/Wanderer/Wanderer Hawlucha"},
    [313] = {"@Pokemon/Wanderer/Wanderer Haxorus"},
    [314] = {"@Pokemon/Wanderer/Wanderer Jolteon"},
    [315] = {"@Pokemon/Wanderer/Wanderer Kingler"},
    [316] = {"@Pokemon/Wanderer/Wanderer Kirlia"},
    [317] = {"@Pokemon/Wanderer/Wanderer Klang"},
    [318] = {"@Pokemon/Wanderer/Wanderer Klinklang"},
    [319] = {"@Pokemon/Wanderer/Wanderer Tyranitar"},
    [320] = {"@Pokemon/Wanderer/Wanderer Kommo-o"},
    [321] = {"@Pokemon/Wanderer/Wanderer Leafeon"},
    [322] = {"@Pokemon/Wanderer/Wanderer Liepard"},
    [323] = {"@Pokemon/Wanderer/Linoone"},
    [324] = {"@Pokemon/Wanderer/Lucario"},
    [325] = {"@Pokemon/Wanderer/Ludicolo"},
    [326] = {"@Pokemon/Wanderer/Machamp"},
    [327] = {"@Pokemon/Wanderer/Machoke"},
    [328] = {"@Pokemon/Wanderer/Manectric"},
    [329] = {"@Pokemon/Wanderer/Mime Jr."},
    [330] = {"@Pokemon/Wanderer/Mimikyu"},
    [331] = {"@Pokemon/Wanderer/Mudsdale"},
    [332] = {"@Pokemon/Wanderer/Musharna"},
    [333] = {"@Pokemon/Wanderer/Ninjask"},
    [334] = {"@Pokemon/Wanderer/Noctowl"},
    [335] = {"@Pokemon/Wanderer/Noivern"},
    [336] = {"@Pokemon/Wanderer/Obstagoon"},
    [337] = {"@Pokemon/Wanderer/Onix"},
    [338] = {"@Pokemon/Wanderer/Orbeetle"},
    [339] = {"@Pokemon/Wanderer/Palpitoad"},
    [340] = {"@Pokemon/Wanderer/Pangoro"},
    [341] = {"@Pokemon/Wanderer/Pelipper"},
    [342] = {"@Pokemon/Wanderer/Perrserker"},
    [343] = {"@Pokemon/Wanderer/Pikachu"},
    [344] = {"@Pokemon/Wanderer/Piloswine"},
    [345] = {"@Pokemon/Wanderer/Quagsire"},
    [346] = {"@Pokemon/Wanderer/Rhydon"},
    [347] = {"@Pokemon/Wanderer/Ribombee"},
    [348] = {"@Pokemon/Wanderer/Roselia"},
    [349] = {"@Pokemon/Wanderer/Roserade"},
    [350] = {"@Pokemon/Wanderer/Sandaconda"},
    [351] = {"@Pokemon/Wanderer/Seismitoad"},
    [352] = {"@Pokemon/Wanderer/Shiftry"},
    [353] = {"@Pokemon/Wanderer/Shiinotic"},
    [354] = {"@Pokemon/Wanderer/Shuckle"},
    [355] = {"@Pokemon/Wanderer/Sigilyph"},
    [356] = {"@Pokemon/Wanderer/Skuntank"},
    [357] = {"@Pokemon/Wanderer/Snorlax"},
    [358] = {"@Pokemon/Wanderer/Steelix"},
    [359] = {"@Pokemon/Wanderer/Sudowoodo"},
    [360] = {"@Pokemon/Wanderer/Sylveon"},
    [361] = {"@Pokemon/Wanderer/Thievul"},
    [362] = {"@Pokemon/Wanderer/Tsareena"},
    [363] = {"@Pokemon/Wanderer/Umbreon"},
    [364] = {"@Pokemon/Wanderer/Unfezant"},
    [365] = {"@Pokemon/Wanderer/Vanillish"},
    [366] = {"@Pokemon/Wanderer/Vanilluxe"},
    [367] = {"@Pokemon/Wanderer/Vaporeon"},
    [368] = {"@Pokemon/Wanderer/Vespiquen"},
    [369] = {"@Pokemon/Wanderer/Vikavolt"},
    [370] = {"@Pokemon/Wanderer/Vileplume"},
    [371] = {"@Pokemon/Wanderer/Weavile"},
    [372] = {"@Pokemon/Wanderer/Xatu"},
    [373] = {"@Pokemon/Wanderer/Seaking"},
    [374] = {"@Pokemon/Wanderer/Lanturn"},
    [375] = {"@Pokemon/Wanderer/Gyarados"},
    [376] = {"@Pokemon/Wanderer/Gastrodon"},
    [377] = {"@Pokemon/Wanderer/Jellicent"},
    [378] = {"@Pokemon/Wanderer/Cloyster"},
    [379] = {"@Pokemon/Wanderer/Milotic"},
    [380] = {"@Pokemon/Wanderer/Lapras"},
    [381] = {"@Pokemon/Wanderer/Wailmer"},
    [382] = {"@Pokemon/Wanderer/Whiscash"},
    [383] = {"@Pokemon/Wanderer/Octillery"}
    [384] = {"@Pokemon/Routes/Rhydon"},
    [385] = {"@Pokemon/Routes/Klang"},
    [386] = {"@Pokemon/Routes/Galarian Mr. Mime"},
    [387] = {"@Pokemon/Routes/Glalie"},
    [388] = {"@Pokemon/Routes/Vanilluxe"},
    [389] = {"@Pokemon/Routes/Cubchoo"},
    [390] = {"@Pokemon/Routes/Abomasnow"},
    [391] = {"@Pokemon/Routes/Beartic"},
    [392] = {"@Pokemon/Routes/Stonjourner"},
    [393] = {"@Pokemon/Routes/Eiscue"},
    [394] = {"@Pokemon/Routes/Duraludon"},
    [395] = {"@Pokemon/Routes/Shuckle"},
    [396] = {"@Pokemon/Routes/Shellos"},
    [397] = {"@Pokemon/Routes/Croagunk"},
    [398] = {"@Pokemon/Routes/Scraggy"},
    [399] = {"@Pokemon/Routes/Binacle"},
    [400] = {"@Pokemon/Routes/Noibat"},
    [401] = {"@Pokemon/Routes/Wimpod"},
    [402] = {"@Pokemon/Routes/Butterfree"},
    [403] = {"@Pokemon/Routes/Galarian Weezing"},
    [404] = {"@Pokemon/Routes/Munna"},
    [405] = {"@Pokemon/Routes/Orbeetle"},
    [406] = {"@Pokemon/Routes/Galarian Stunfisk"},
    [407] = {"@Pokemon/Routes/Impidimp"},
    [408] = {"@Pokemon/Routes/Koffing"},
    [409] = {"@Pokemon/Routes/Noctowl"},
    [410] = {"@Pokemon/Routes/Sudowoodo"},
    [411] = {"@Pokemon/Routes/Salandit"},
    [412] = {"@Pokemon/Routes/Hatenna"},
    [413] = {"@Pokemon/Routes/Galarian Ponyta"},
    [414] = {"@Pokemon/Routes/Phantump"},
    [415] = {"@Pokemon/Routes/Shiinotic"},
    [416] = {"@Pokemon/Routes/Oranguru"},
    [417] = {"@Pokemon/Routes/Passimian"},
    [418] = {"@Pokemon/Routes/Sinistea"},
    [419] = {"@Pokemon/Routes/Hattrem"},
    [420] = {"@Pokemon/Routes/Morgrem"},
    [421] = {"@Pokemon/Routes/Indeedee"},
}
